name: Generate MO
on:
  push:
    branches: [ main ]
    paths:
    - '**.po'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs: 
  run:
    
    name: Generate mo
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2 
      
    - name: msgfmt
      # You may pin to the exact commit or the version.
      # uses: whtsky/msgfmt-action@6b2181f051b002182d01a1e1f1aff216230c5a4d
      uses: whtsky/msgfmt-action@20190305
    - name: Generate mo
      run:  find . -type f -name "*.po" -exec msgfmt {} -o {}.mo \;

    - name: Commit changes
      uses: EndBug/add-and-commit@v5.1.0
      with:
       
        message: "Generate mo"
    - name: Push changes
 
      uses: actions-go/push@v1
  
